Добавление account - в которой храниться информация об аккаунте;
AlexQD/ipphone pull request #1
Opened 2020-11-17 19:16 UTC by AlexQD

Добавлен account - в которой храниться информация об аккаунте;
Добавлена history - в которой храниться история звонков

2020-11-17 19:42 UTC, Korgutlova requested changes
Исправить замечания

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/AccountController.java
> +    private AccountService accountService;
необходимо указать final модификатор, тоже самое для остальных сервисов в других контроллерах

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +            historyService.save(historys.getHistory_array().get(i));
можно заменить на контрукцию со Stream API и желательно вынести в сервис historyService где будет метод save принимающие на вход список

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    public String Index(Model model)  {
название методов должно начинаться с маленькой буквы index, getHistory и так далее

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/dto/HistoryDto.java
> +    private Long uid_atc;
в java не используется нижнее подчеркивание , преимущественнен CamelCase то есть uid_atc -> uidAtc  (тоже самое относится к методам, и другим переменным, проверь это и в других файлах)

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    public String getTypePrint() {
можно заменить эту переменную type в тип данных enum, где в бд будет хранится значения in, out, missed, а отображаемая информация уже на русском. пример https://www.baeldung.com/java-enum-values#adding-constructor

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/Historys.java
> +    private ArrayList<History> history_array;
привести к CamelCase

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/Historys.java
> +//        for (int i = 0; i < historys.getHistory_array().size(); ++i) {
удалить неиспользуемый код

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/services/HistoryServiceImpl.java
> +//        History history = new History();
удалить неиспользуемый код

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private AccountService account_formater;
сервисы не объявляют внутри классов @Entity

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
данный список не должен быть у сущности аккаунт? иначе как сущность история может иметь список историй вызовов

2020-11-17 19:42 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private String account;
я думаю здесь нужно сделать ссылку на существующую @Entity аккаунт, и тогда аккаунт будет иметь (знать свой) список с историей вызовов и не нужно будет создавать дополнительный класс `Historys`, а все его методы, вынести в HistoryService

2020-11-17 19:42 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    account         varchar(1000) ,
в отдельном sql скрипте нужно также добавить FK на аккаунт

2020-11-17 19:42 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    type            varchar(1000) ,
также необходимо подумать о кол-ве выделяемой памяти (varchar(1000)) для некоторых полей это избыточно.

2020-11-18 05:54 UTC, ramilmm commented on pom.xml
> +			<artifactId>spring-boot-starter-thymeleaf</artifactId>
эта зависимость нужна для REST?

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
неправильный нейминг переменной. camelCase

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private AccountService account_formater;
неправильный нейминг переменной. camelCase

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/model/Historys.java
> +    public Historys missing_call(History history){
Стоп. Какие методы в модели?
Модель - это просто описание модели в базе данных. Здесь не должно быть никаких Autowired, Services, Repositories. Здесь нет логики. Это описание модели.

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/repository/AccountRepository.java
> +    Optional<Account> findById(Long id);
не нужно оверрайдить этот метод. Он уже реализован в JpaRepository. Можно просто использовать готовую реализацию

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/repository/AccountRepository.java
> +    List<Account> findAll();
не нужно оверрайдить этот метод. Он уже реализован в JpaRepository. Можно просто использовать готовую реализацию

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/repository/AccountRepository.java
> +    Optional<Account> findById(Long id);
Здесь может быть просто пустой репозиторий, если нужны только эти 2 метода

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/AccountServiceImpl.java
> +    public Account getAccounttoHistory(History history){
может @Override добавить?

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +    public String request_history()  {
это public метод или private?

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +                .uri(URI.create("https://vats000000.megapbx.ru/sys/crm_api.wcgp"))
лучше вынести значение в поле или конфиг

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +        data.put("token", "0000-0000-0000-0000-0000");
токен опасно так хранить. Тоже лучше вынести в параметр или конфиг

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +            builder.append(URLEncoder.encode(entry.getValue().toString(), StandardCharsets.UTF_8));
builder.append()
           .append()
           .append()

2020-11-18 05:54 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +            history.setType(words[1]);
в каком-то странном формате приходят данные. Что если в АПИ добавят какой-нибудь новый параметр в середину ответа? тогда весь этот код будет неправильно работать

2020-11-18 05:56 UTC, ramilmm commented on pom.xml
> +			<artifactId>spring-boot-starter-thymeleaf</artifactId>
теперь вижу что нужна. Thymeleaf очень редко применяется в коммерческих проектах, поэтому мы выбрали формат REST API для обучения. Можешь дальше делать с таймлифом, можешь переделать на РЕСТ.

2020-11-18 19:56 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/controllers/AccountController.java
> +    private AccountService accountService;
исправлено

2020-11-18 19:56 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    public String Index(Model model)  {
исправлено

2020-11-18 19:56 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/dto/HistoryDto.java
> +    private Long uid_atc;
исправлено

2020-11-18 19:57 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private AccountService account_formater;
исправлено

2020-11-18 20:03 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
В данном случае если мы смотрим информацию о звонках за сутки - сюда будут загружаться все звонки с этого номера за сутки. Данное поле удобно использовать чтобы провести например аналитику пропущенных звонков, можно видеть дозвонился человек или нет.

2020-11-18 20:03 UTC, AlexQD commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    type            varchar(1000) ,
исправлено

2020-11-18 20:13 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/AccountController.java
> +    private AccountService accountService;
@AlexQD подразумевалось поставить final модификатор для сервиса, а не контроллера.

2020-11-19 06:39 UTC, AlexQD commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    account         varchar(1000) ,
исправлено

2020-11-19 06:40 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
исправлено

2020-11-19 06:41 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private AccountService account_formater;
исправлено,убрано из модели

2020-11-19 06:41 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/Historys.java
> +    public Historys missing_call(History history){
исправлено

2020-11-19 06:41 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/repository/AccountRepository.java
> +    Optional<Account> findById(Long id);
исправлено

2020-11-19 06:42 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +    public String request_history()  {
private, поправлено

2020-11-19 06:42 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +                .uri(URI.create("https://vats000000.megapbx.ru/sys/crm_api.wcgp"))
исправлено

2020-11-19 06:42 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +        data.put("token", "0000-0000-0000-0000-0000");
исправлено

2020-11-19 06:43 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +            builder.append(URLEncoder.encode(entry.getValue().toString(), StandardCharsets.UTF_8));
исправлено

2020-11-19 06:43 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +            history.setType(words[1]);
так оттдает облачная атс https://firma.megapbx.ru/SkinFiles/firma.megapbx.ru/Megafon3/crm_rest_api.pdf

2020-11-19 09:47 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
@AlexQD в чем проблема хранить в базе данных такую свзять у нас есть Account, History (который хранит связь с аккаунтом, кто выполнял эти звонки), в репозитории можно реализовать метод вытащить список History по опеределенному аккаунту, за такой то день. это просто решается фильтрацией.

2020-11-19 11:03 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
Это поле используется для быстрого получения статистики( например за час) минуя бд обращаясь напрямую к api атс.
Account -это профиль, того кому поступает звонок. Пропущенные вызовы - фиксируются по полю client, они обезличенные просто номер. 

Список звонков с номера 7777777777 (как раз помещается в поле all_call_this_number):
Пропущенный 7777777777 Thu Nov 19 10:56:27 SAMT 2020 123
Входящий 7777777777 Thu Nov 19 09:46:31 SAMT 2020 282
Пропущенный 7777777777 Thu Nov 19 08:56:27 SAMT 2020 123
Пропущенный 7777777777 Thu Nov 19 08:47:20 SAMT 2020 139
Пропущенный 7777777777 Thu Nov 19 08:35:11 SAMT 2020 50
Пропущенный 7777777777 Thu Nov 19 08:30:07 SAMT 2020 95
так как на последний момент Thu Nov 19 10:56:27 - был пропущенный вызов, значит звонок с номера 7777777777 считается пропущенным.
Используя это поле нужно всего лишь выбрать список всех пропущенных звонков удалить дубли , пройти по нему циклом и записать в это поле получившийся список, последняя запись (с поздней датой) будет статусом дозвонился человек или нет, и остальные номера для аналитики, по общей картине звонков с этого номера.

Наверное надо описать логику всего приложения, прикрепив доку в проект.

2020-11-19 16:48 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    private Historys all_call_this_number;
@AlexQD да ты выбрал проект уже близкий к продакшену, сходу сложно понять что имеешь ты ввиду )

2020-11-19 18:20 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            historyService.save(historysDto.getHistoryArray().get(i));
может использовать saveAll()?

2020-11-19 18:20 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            System.out.println(historys.getHistoryArray().get(i).getUidAtc());
лучше использовать современные возможности языка. Тут например можно historys.getHistoryArray().forEach(history -> ...)

2020-11-19 18:20 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            hashMap.put(historys.getHistoryArray().get(i).getClient(),historys.getHistoryArray().get(i));
.forEach()

2020-11-19 18:20 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            if (historys.getHistoryArray().get(i).getClient().equals(history.getClient())){
historys.getHistoryArray().get(i) было бы красивее перенести в отдельную переменную чтобы смотрелось проще

2020-11-22 17:52 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +            historyService.save(historys.getHistory_array().get(i));
исправлено, вынесено в service

2020-11-22 17:52 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +    public String getTypePrint() {
исправлено

2020-11-22 17:53 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            System.out.println(historys.getHistoryArray().get(i).getUidAtc());
исправлено

2020-11-22 17:53 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            hashMap.put(historys.getHistoryArray().get(i).getClient(),historys.getHistoryArray().get(i));
исправлено

2020-11-22 17:53 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +            if (historys.getHistoryArray().get(i).getClient().equals(history.getClient())){
исправлено на .forEach()

2020-11-23 16:01 UTC, Korgutlova reviewed
Вот еще минорные замечания :)

2020-11-23 16:01 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/AccountController.java
> +    private AccountService accountService;
@AlexQD необходимо было сделать вот так `private final AccountService accountService;`

2020-11-23 16:01 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +@Controller
`@RestController`

2020-11-23 16:01 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    private RequestService requestService;
@AlexQD необходимо было сделать вот так `private final RequestService requestService;` в похожих местах также

2020-11-23 16:01 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/dto/AccountDto.java
> +    public String getPhone() {
можно использовать lombok для того чтобы не писать каждый раз getter и setter

2020-11-23 16:01 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +//            case "missed": return "Пропущенный";
если теперь это нормально работает с enumeration лучше убирать закомментированный код

2020-11-23 18:52 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/dto/AccountDto.java
> +    public String getPhone() {
об этом мы будем говорить на следующем занятии)

2020-11-23 19:01 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/model/TypeCall.java
> +    missed("Пропущенный");
IN, OUT, MISSED.
Енамы капсом пишут, как правило

2020-11-23 19:01 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +    public void save(HistorysDto historysDto){
@Override?

2020-11-23 19:01 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +    public void print(HistorysDto historys){
@Override?

2020-11-23 19:01 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/HistorysServiceImpl.java
> +    public Historys missingCall(Historys historys, History history){
эти методы не нужно добавить в HistorysService?

2020-11-23 19:01 UTC, ramilmmk commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +public class RequestService {
Возможно стоит переименовать этот класс с сервиса на какой-нибудь ApiClient, CloudPhoneClient, CloudPhoneUtil.......
Пометить как @Component

2020-11-24 05:07 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    private RequestService requestService;
![изображение](https://user-images.githubusercontent.com/6279731/100051057-59850900-2e34-11eb-83cb-7ee89e986e44.png)

2020-11-24 05:07 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    private RequestService requestService;
А можно поподробнее, зачем нам это нужно?

2020-11-24 08:13 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/model/History.java
> +//            case "missed": return "Пропущенный";
исправлено

2020-11-24 08:13 UTC, AlexQD commented on src/main/java/ru/radcenter/ipphone/services/RequestService.java
> +public class RequestService {
исправлено

2020-11-25 22:57 UTC, Korgutlova commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    private RequestService requestService;
@AlexQD чтобы инициализировать данную переменную единожды, и обезопасить себя от ее перезаписи и изменений.

2020-11-25 22:58 UTC, Korgutlova approved these changes

2020-11-26 19:04 UTC, ramilmm commented on src/main/java/ru/radcenter/ipphone/controllers/HistoryController.java
> +    private RequestService requestService;
@AlexQD 

Если делать через final, то нужно инициализировать переменную через конструктор.

private final RequestService requestService;

public HistoryController(RequestService requestService) {
this.requestService = requestService;
}

Либо используя Lombok

Вешаем аннотацию @RequiredArgsConstructor и оставляем только private final RequestService requestServce

2020-11-26 19:06 UTC, ramilmm commented
Доделай по моим комментам и можешь мёржить

2020-12-05 06:48 UTC, merged